import {
  Avatar,
  Box,
  Button,
  Card,
  CardBody,
  Container,
  HStack,
  VStack,
  Text,
  Heading,
  Image,
} from "@chakra-ui/react";
import Head from "next/head";
import Comment from "../components/comment";
import data from "../../data/data.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box as="main" w="full" minH="100vh" py={10} bg="veryLightGray.500">
        <Container maxW="container.md">
          <VStack rowGap={6}>
            {data.comments.map((comment) => (
              <Comment
                key={comment.id}
                id={comment.id}
                content={comment.content}
                createdAt={comment.createdAt}
                score={comment.score}
                user={comment.user}
                replies={comment.replies}
              />
            ))}
          </VStack>
        </Container>
      </Box>
    </>
  );
}
